spring:
  datasource:
    url: jdbc:mysql://localhost:3306/educationcenter?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootroot

